

# This file was *autogenerated* from the file ex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_100000000000000 = Integer(100000000000000); _sage_const_107163998661720 = Integer(107163998661720); _sage_const_36253030834483 = Integer(36253030834483)
for i in range(_sage_const_1 ,_sage_const_100000000000000 ):
	if(is_prime(_sage_const_107163998661720  * i + _sage_const_36253030834483 )):
		print(_sage_const_107163998661720  * i + _sage_const_36253030834483 )

